# Generated by Django 4.1.2 on 2022-11-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_lyric_song_foreign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
    ]
